feat: paramCase Service logger
cordiverse/cordis pull request #10
Opened 2024-02-27 16:00 UTC by CyanChanges

2024-04-24 13:34 UTC, shigma reviewed
`service.name` is already param-cased.

2024-04-24 13:37 UTC, shigma requested changes

2024-04-24 13:37 UTC, shigma commented on packages/cordis/src/index.ts
> +import { paramCase } from 'cosmokit'
Please place `import` before `export`.

2024-12-01 06:36 UTC, CyanChanges commented
Well, outdated

2024-12-01 06:36 UTC, closed without merging