feat: warning when plugin on a disposed scope
cordiverse/cordis pull request #5
Opened 2023-10-26 16:58 UTC by CyanChanges

我觉得可以 throw Error？（

2023-10-27 05:27 UTC, shigma requested changes

2023-10-27 05:27 UTC, shigma commented on src/registry.ts
> +    if (context.scope.status == 'disposed') {
不应该使用 status（这个是需要手动更新的），应该判断 `scope.uid === null`。

2023-10-27 05:28 UTC, shigma commented
> 我觉得可以 throw Error？（

程序能正常运行，我觉得不需要 throw。

2023-10-27 10:43 UTC, CyanChanges commented
> > 我觉得可以 throw Error？（
> 
> 程序能正常运行，我觉得不需要 throw。

主要是关于返回的问题，因为压根没有创建 Scope，所以只能 undefined/null，后面如果用到了
可能会炸，throw 了就不会跑到后面就不炸了（

2023-10-30 07:24 UTC, shigma approved these changes

2023-10-30 07:25 UTC, merged